/*
 * gateway.marvel.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Cable
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.marvel.model;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.LocalDate;

/**
 * ComicDate
 */

public class ComicDate {
  @SerializedName("type")
  private String type = null;

  @SerializedName("date")
  private LocalDate date = null;

  public ComicDate type(String type) {
    this.type = type;
    return this;
  }

   /**
   * A description of the date (e.g. onsale date, FOC date).
   * @return type
  **/
  @ApiModelProperty(value = "A description of the date (e.g. onsale date, FOC date).")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ComicDate date(LocalDate date) {
    this.date = date;
    return this;
  }

   /**
   * The date.
   * @return date
  **/
  @ApiModelProperty(value = "The date.")
  public LocalDate getDate() {
    return date;
  }

  public void setDate(LocalDate date) {
    this.date = date;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    ComicDate comicDate = (ComicDate) o;
    return ObjectUtils.equals(this.type, comicDate.type) &&
    ObjectUtils.equals(this.date, comicDate.date);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(type, date);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComicDate {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

