/*
 * gateway.marvel.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Cable
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.marvel.model;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.marvel.model.ComicList;
import com.marvel.model.EventList;
import com.marvel.model.Image;
import com.marvel.model.SeriesList;
import com.marvel.model.StoryList;
import com.marvel.model.Url;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.LocalDate;

/**
 * Creator
 */

public class Creator {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("firstName")
  private String firstName = null;

  @SerializedName("middleName")
  private String middleName = null;

  @SerializedName("lastName")
  private String lastName = null;

  @SerializedName("suffix")
  private String suffix = null;

  @SerializedName("fullName")
  private String fullName = null;

  @SerializedName("modified")
  private LocalDate modified = null;

  @SerializedName("resourceURI")
  private String resourceURI = null;

  @SerializedName("urls")
  private List<Url> urls = null;

  @SerializedName("thumbnail")
  private Image thumbnail = null;

  @SerializedName("series")
  private SeriesList series = null;

  @SerializedName("stories")
  private StoryList stories = null;

  @SerializedName("comics")
  private ComicList comics = null;

  @SerializedName("events")
  private EventList events = null;

  public Creator id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * The unique ID of the creator resource.
   * @return id
  **/
  @ApiModelProperty(value = "The unique ID of the creator resource.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Creator firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * The first name of the creator.
   * @return firstName
  **/
  @ApiModelProperty(value = "The first name of the creator.")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public Creator middleName(String middleName) {
    this.middleName = middleName;
    return this;
  }

   /**
   * The middle name of the creator.
   * @return middleName
  **/
  @ApiModelProperty(value = "The middle name of the creator.")
  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public Creator lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * The last name of the creator.
   * @return lastName
  **/
  @ApiModelProperty(value = "The last name of the creator.")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public Creator suffix(String suffix) {
    this.suffix = suffix;
    return this;
  }

   /**
   * The suffix or honorific for the creator.
   * @return suffix
  **/
  @ApiModelProperty(value = "The suffix or honorific for the creator.")
  public String getSuffix() {
    return suffix;
  }

  public void setSuffix(String suffix) {
    this.suffix = suffix;
  }

  public Creator fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * The full name of the creator (a space-separated concatenation of the above four fields).
   * @return fullName
  **/
  @ApiModelProperty(value = "The full name of the creator (a space-separated concatenation of the above four fields).")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public Creator modified(LocalDate modified) {
    this.modified = modified;
    return this;
  }

   /**
   * The date the resource was most recently modified.
   * @return modified
  **/
  @ApiModelProperty(value = "The date the resource was most recently modified.")
  public LocalDate getModified() {
    return modified;
  }

  public void setModified(LocalDate modified) {
    this.modified = modified;
  }

  public Creator resourceURI(String resourceURI) {
    this.resourceURI = resourceURI;
    return this;
  }

   /**
   * The canonical URL identifier for this resource.
   * @return resourceURI
  **/
  @ApiModelProperty(value = "The canonical URL identifier for this resource.")
  public String getResourceURI() {
    return resourceURI;
  }

  public void setResourceURI(String resourceURI) {
    this.resourceURI = resourceURI;
  }

  public Creator urls(List<Url> urls) {
    this.urls = urls;
    return this;
  }

  public Creator addUrlsItem(Url urlsItem) {
    if (this.urls == null) {
      this.urls = new ArrayList<Url>();
    }
    this.urls.add(urlsItem);
    return this;
  }

   /**
   * A set of public web site URLs for the resource.
   * @return urls
  **/
  @ApiModelProperty(value = "A set of public web site URLs for the resource.")
  public List<Url> getUrls() {
    return urls;
  }

  public void setUrls(List<Url> urls) {
    this.urls = urls;
  }

  public Creator thumbnail(Image thumbnail) {
    this.thumbnail = thumbnail;
    return this;
  }

   /**
   * The representative image for this creator.
   * @return thumbnail
  **/
  @ApiModelProperty(value = "The representative image for this creator.")
  public Image getThumbnail() {
    return thumbnail;
  }

  public void setThumbnail(Image thumbnail) {
    this.thumbnail = thumbnail;
  }

  public Creator series(SeriesList series) {
    this.series = series;
    return this;
  }

   /**
   * A resource list containing the series which feature work by this creator.
   * @return series
  **/
  @ApiModelProperty(value = "A resource list containing the series which feature work by this creator.")
  public SeriesList getSeries() {
    return series;
  }

  public void setSeries(SeriesList series) {
    this.series = series;
  }

  public Creator stories(StoryList stories) {
    this.stories = stories;
    return this;
  }

   /**
   * A resource list containing the stories which feature work by this creator.
   * @return stories
  **/
  @ApiModelProperty(value = "A resource list containing the stories which feature work by this creator.")
  public StoryList getStories() {
    return stories;
  }

  public void setStories(StoryList stories) {
    this.stories = stories;
  }

  public Creator comics(ComicList comics) {
    this.comics = comics;
    return this;
  }

   /**
   * A resource list containing the comics which feature work by this creator.
   * @return comics
  **/
  @ApiModelProperty(value = "A resource list containing the comics which feature work by this creator.")
  public ComicList getComics() {
    return comics;
  }

  public void setComics(ComicList comics) {
    this.comics = comics;
  }

  public Creator events(EventList events) {
    this.events = events;
    return this;
  }

   /**
   * A resource list containing the events which feature work by this creator.
   * @return events
  **/
  @ApiModelProperty(value = "A resource list containing the events which feature work by this creator.")
  public EventList getEvents() {
    return events;
  }

  public void setEvents(EventList events) {
    this.events = events;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    Creator creator = (Creator) o;
    return ObjectUtils.equals(this.id, creator.id) &&
    ObjectUtils.equals(this.firstName, creator.firstName) &&
    ObjectUtils.equals(this.middleName, creator.middleName) &&
    ObjectUtils.equals(this.lastName, creator.lastName) &&
    ObjectUtils.equals(this.suffix, creator.suffix) &&
    ObjectUtils.equals(this.fullName, creator.fullName) &&
    ObjectUtils.equals(this.modified, creator.modified) &&
    ObjectUtils.equals(this.resourceURI, creator.resourceURI) &&
    ObjectUtils.equals(this.urls, creator.urls) &&
    ObjectUtils.equals(this.thumbnail, creator.thumbnail) &&
    ObjectUtils.equals(this.series, creator.series) &&
    ObjectUtils.equals(this.stories, creator.stories) &&
    ObjectUtils.equals(this.comics, creator.comics) &&
    ObjectUtils.equals(this.events, creator.events);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(id, firstName, middleName, lastName, suffix, fullName, modified, resourceURI, urls, thumbnail, series, stories, comics, events);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Creator {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    suffix: ").append(toIndentedString(suffix)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    resourceURI: ").append(toIndentedString(resourceURI)).append("\n");
    sb.append("    urls: ").append(toIndentedString(urls)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    series: ").append(toIndentedString(series)).append("\n");
    sb.append("    stories: ").append(toIndentedString(stories)).append("\n");
    sb.append("    comics: ").append(toIndentedString(comics)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

