/*
 * gateway.marvel.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Cable
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.marvel.model;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.marvel.model.CharacterList;
import com.marvel.model.ComicList;
import com.marvel.model.CreatorList;
import com.marvel.model.EventList;
import com.marvel.model.Image;
import com.marvel.model.SeriesSummary;
import com.marvel.model.StoryList;
import com.marvel.model.Url;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.LocalDate;

/**
 * Series
 */

public class Series {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("resourceURI")
  private String resourceURI = null;

  @SerializedName("urls")
  private List<Url> urls = null;

  @SerializedName("startYear")
  private Integer startYear = null;

  @SerializedName("endYear")
  private Integer endYear = null;

  @SerializedName("rating")
  private String rating = null;

  @SerializedName("modified")
  private LocalDate modified = null;

  @SerializedName("thumbnail")
  private Image thumbnail = null;

  @SerializedName("comics")
  private ComicList comics = null;

  @SerializedName("stories")
  private StoryList stories = null;

  @SerializedName("events")
  private EventList events = null;

  @SerializedName("characters")
  private CharacterList characters = null;

  @SerializedName("creators")
  private CreatorList creators = null;

  @SerializedName("next")
  private SeriesSummary next = null;

  @SerializedName("previous")
  private SeriesSummary previous = null;

  public Series id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * The unique ID of the series resource.
   * @return id
  **/
  @ApiModelProperty(value = "The unique ID of the series resource.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Series title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The canonical title of the series.
   * @return title
  **/
  @ApiModelProperty(value = "The canonical title of the series.")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Series description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A description of the series.
   * @return description
  **/
  @ApiModelProperty(value = "A description of the series.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Series resourceURI(String resourceURI) {
    this.resourceURI = resourceURI;
    return this;
  }

   /**
   * The canonical URL identifier for this resource.
   * @return resourceURI
  **/
  @ApiModelProperty(value = "The canonical URL identifier for this resource.")
  public String getResourceURI() {
    return resourceURI;
  }

  public void setResourceURI(String resourceURI) {
    this.resourceURI = resourceURI;
  }

  public Series urls(List<Url> urls) {
    this.urls = urls;
    return this;
  }

  public Series addUrlsItem(Url urlsItem) {
    if (this.urls == null) {
      this.urls = new ArrayList<Url>();
    }
    this.urls.add(urlsItem);
    return this;
  }

   /**
   * A set of public web site URLs for the resource.
   * @return urls
  **/
  @ApiModelProperty(value = "A set of public web site URLs for the resource.")
  public List<Url> getUrls() {
    return urls;
  }

  public void setUrls(List<Url> urls) {
    this.urls = urls;
  }

  public Series startYear(Integer startYear) {
    this.startYear = startYear;
    return this;
  }

   /**
   * The first year of publication for the series.
   * @return startYear
  **/
  @ApiModelProperty(value = "The first year of publication for the series.")
  public Integer getStartYear() {
    return startYear;
  }

  public void setStartYear(Integer startYear) {
    this.startYear = startYear;
  }

  public Series endYear(Integer endYear) {
    this.endYear = endYear;
    return this;
  }

   /**
   * The last year of publication for the series (conventionally, 2099 for ongoing series) .
   * @return endYear
  **/
  @ApiModelProperty(value = "The last year of publication for the series (conventionally, 2099 for ongoing series) .")
  public Integer getEndYear() {
    return endYear;
  }

  public void setEndYear(Integer endYear) {
    this.endYear = endYear;
  }

  public Series rating(String rating) {
    this.rating = rating;
    return this;
  }

   /**
   * The age-appropriateness rating for the series.
   * @return rating
  **/
  @ApiModelProperty(value = "The age-appropriateness rating for the series.")
  public String getRating() {
    return rating;
  }

  public void setRating(String rating) {
    this.rating = rating;
  }

  public Series modified(LocalDate modified) {
    this.modified = modified;
    return this;
  }

   /**
   * The date the resource was most recently modified.
   * @return modified
  **/
  @ApiModelProperty(value = "The date the resource was most recently modified.")
  public LocalDate getModified() {
    return modified;
  }

  public void setModified(LocalDate modified) {
    this.modified = modified;
  }

  public Series thumbnail(Image thumbnail) {
    this.thumbnail = thumbnail;
    return this;
  }

   /**
   * The representative image for this series.
   * @return thumbnail
  **/
  @ApiModelProperty(value = "The representative image for this series.")
  public Image getThumbnail() {
    return thumbnail;
  }

  public void setThumbnail(Image thumbnail) {
    this.thumbnail = thumbnail;
  }

  public Series comics(ComicList comics) {
    this.comics = comics;
    return this;
  }

   /**
   * A resource list containing comics in this series.
   * @return comics
  **/
  @ApiModelProperty(value = "A resource list containing comics in this series.")
  public ComicList getComics() {
    return comics;
  }

  public void setComics(ComicList comics) {
    this.comics = comics;
  }

  public Series stories(StoryList stories) {
    this.stories = stories;
    return this;
  }

   /**
   * A resource list containing stories which occur in comics in this series.
   * @return stories
  **/
  @ApiModelProperty(value = "A resource list containing stories which occur in comics in this series.")
  public StoryList getStories() {
    return stories;
  }

  public void setStories(StoryList stories) {
    this.stories = stories;
  }

  public Series events(EventList events) {
    this.events = events;
    return this;
  }

   /**
   * A resource list containing events which take place in comics in this series.
   * @return events
  **/
  @ApiModelProperty(value = "A resource list containing events which take place in comics in this series.")
  public EventList getEvents() {
    return events;
  }

  public void setEvents(EventList events) {
    this.events = events;
  }

  public Series characters(CharacterList characters) {
    this.characters = characters;
    return this;
  }

   /**
   * A resource list containing characters which appear in comics in this series.
   * @return characters
  **/
  @ApiModelProperty(value = "A resource list containing characters which appear in comics in this series.")
  public CharacterList getCharacters() {
    return characters;
  }

  public void setCharacters(CharacterList characters) {
    this.characters = characters;
  }

  public Series creators(CreatorList creators) {
    this.creators = creators;
    return this;
  }

   /**
   * A resource list of creators whose work appears in comics in this series.
   * @return creators
  **/
  @ApiModelProperty(value = "A resource list of creators whose work appears in comics in this series.")
  public CreatorList getCreators() {
    return creators;
  }

  public void setCreators(CreatorList creators) {
    this.creators = creators;
  }

  public Series next(SeriesSummary next) {
    this.next = next;
    return this;
  }

   /**
   * A summary representation of the series which follows this series.
   * @return next
  **/
  @ApiModelProperty(value = "A summary representation of the series which follows this series.")
  public SeriesSummary getNext() {
    return next;
  }

  public void setNext(SeriesSummary next) {
    this.next = next;
  }

  public Series previous(SeriesSummary previous) {
    this.previous = previous;
    return this;
  }

   /**
   * A summary representation of the series which preceded this series.
   * @return previous
  **/
  @ApiModelProperty(value = "A summary representation of the series which preceded this series.")
  public SeriesSummary getPrevious() {
    return previous;
  }

  public void setPrevious(SeriesSummary previous) {
    this.previous = previous;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    Series series = (Series) o;
    return ObjectUtils.equals(this.id, series.id) &&
    ObjectUtils.equals(this.title, series.title) &&
    ObjectUtils.equals(this.description, series.description) &&
    ObjectUtils.equals(this.resourceURI, series.resourceURI) &&
    ObjectUtils.equals(this.urls, series.urls) &&
    ObjectUtils.equals(this.startYear, series.startYear) &&
    ObjectUtils.equals(this.endYear, series.endYear) &&
    ObjectUtils.equals(this.rating, series.rating) &&
    ObjectUtils.equals(this.modified, series.modified) &&
    ObjectUtils.equals(this.thumbnail, series.thumbnail) &&
    ObjectUtils.equals(this.comics, series.comics) &&
    ObjectUtils.equals(this.stories, series.stories) &&
    ObjectUtils.equals(this.events, series.events) &&
    ObjectUtils.equals(this.characters, series.characters) &&
    ObjectUtils.equals(this.creators, series.creators) &&
    ObjectUtils.equals(this.next, series.next) &&
    ObjectUtils.equals(this.previous, series.previous);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(id, title, description, resourceURI, urls, startYear, endYear, rating, modified, thumbnail, comics, stories, events, characters, creators, next, previous);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Series {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    resourceURI: ").append(toIndentedString(resourceURI)).append("\n");
    sb.append("    urls: ").append(toIndentedString(urls)).append("\n");
    sb.append("    startYear: ").append(toIndentedString(startYear)).append("\n");
    sb.append("    endYear: ").append(toIndentedString(endYear)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    comics: ").append(toIndentedString(comics)).append("\n");
    sb.append("    stories: ").append(toIndentedString(stories)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    characters: ").append(toIndentedString(characters)).append("\n");
    sb.append("    creators: ").append(toIndentedString(creators)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    previous: ").append(toIndentedString(previous)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

